refactor: fiat value placement on action screens
ArdentHQ/arkconnect-extension pull request #169
Opened 2024-03-14 17:40 UTC by alfonsobries

## Summary

Closes https://app.clickup.com/t/86drkydvy

## Checklist

- [ ] I checked that both `pnpm dev` and `pnpm dev:bare` work as intended
- [ ] I checked the basic extension interactions and made sure wallet selection works
- [ ] I checked my UI changes against the design and there are no notable differences, including responsiveness
- [ ] I checked my (code) changes for obvious issues, debug statements and commented code
- [ ] I opened a corresponding card on Clickup for any remaining TODOs in my code
- [ ] I added a short description on how to test this PR _(if necessary)_
- [ ] Ready to be merged

2024-03-15 13:53 UTC, samharperpittam requested changes
@alfonsobries  - Can you check if the fiat values populate for you when sending a tx on mainnet? They all seems to be `0.00` for me.

![image](https://github.com/ArdentHQ/arkconnect-extension/assets/44671015/b2896331-5910-426f-aef3-77ae220f830a)

2024-03-15 15:51 UTC, alfonsobries commented
@samharperpittam did you see the fiat values on `develop`? I didnt really changed any logic think we can handle that as a separated task,

For the moment Im going to mark as ready again while confirming

2024-03-15 15:56 UTC, samharperpittam commented
hmmm you are correct @alfonsobries  - seems it's not working on develop either.

2024-03-18 12:35 UTC, shahin-hq approved these changes

2024-03-18 16:59 UTC, samharperpittam approved these changes

2024-03-18 21:14 UTC, merged