feat: add transaction pending state
ArdentHQ/arkconnect-extension pull request #201
Opened 2024-03-27 15:05 UTC by shahin-hq

## Summary
Closes: https://app.clickup.com/t/86drqgud1
Design: https://www.figma.com/file/GCqNSpm379nEO9IEHQl2dt/ARK-Connect?node-id=9623%3A25026&mode=dev

## Checklist

- [ ] I checked that both `pnpm dev` and `pnpm dev:bare` work as intended
- [ ] I checked the basic extension interactions and made sure wallet selection works
- [ ] I checked my UI changes against the design and there are no notable differences, including responsiveness
- [ ] I checked my (code) changes for obvious issues, debug statements and commented code
- [ ] I opened a corresponding card on Clickup for any remaining TODOs in my code
- [ ] I added a short description on how to test this PR _(if necessary)_
- [ ] Ready to be merged

2024-03-27 16:58 UTC, samharperpittam submitted a review, later dismissed

2024-03-28 12:40 UTC, samharperpittam approved these changes

2024-03-28 15:19 UTC, ItsANameToo requested changes

2024-03-28 15:19 UTC, ItsANameToo commented on src/pages/VoteApproved.tsx
> +                                This transaction is pending confirmation
use a translation

2024-03-28 15:19 UTC, ItsANameToo commented on src/pages/TransactionApproved.tsx
> +                                This transaction is pending confirmation
use a translation

2024-03-28 15:35 UTC, ItsANameToo approved these changes

2024-03-28 15:35 UTC, merged