feat: add "view more" button for transactions section
ArdentHQ/arkconnect-extension pull request #218
Opened 2024-04-12 07:40 UTC by patricio0312rev

# [[dashboard] add "view more" button](https://app.clickup.com/t/86dt7tprj)

## Summary

- Styling for hover state of `secondary` button variant has been updated.
- Query to fetch transactions has been updated.
- "View more" button has been added to transactions list in case we have more than 10 transactions.

<img width="369" alt="image" src="https://github.com/ArdentHQ/arkconnect-extension/assets/55117912/2b08a75c-394f-4f1b-9ed1-0bf00d807ff9">

## Checklist

- [ ] I checked that both `pnpm dev` and `pnpm dev:bare` work as intended
- [ ] I checked the basic extension interactions and made sure wallet selection works
- [ ] I checked my UI changes against the design and there are no notable differences, including responsiveness
- [ ] I checked my (code) changes for obvious issues, debug statements and commented code
- [ ] I opened a corresponding card on Clickup for any remaining TODOs in my code
- [ ] I added a short description on how to test this PR _(if necessary)_
- [ ] Ready to be merged

2024-04-12 11:32 UTC, samharperpittam requested changes
I see a button but clicking it doesn't open explorer?

2024-04-15 10:03 UTC, samharperpittam approved these changes

2024-04-17 10:47 UTC, ItsANameToo requested changes

2024-04-17 10:47 UTC, ItsANameToo commented on src/components/home/LatestTransactions.blocks.tsx
> +                                : `${constants.ARKSCAN_TEST_ADDRESSES}/${primaryWallet?.address()}`
there is a `getExplorerDomain` helper to handle this

2024-04-17 17:00 UTC, ItsANameToo approved these changes

2024-04-17 17:00 UTC, merged