feat: handle multipayment details
ArdentHQ/arkconnect-extension pull request #236
Opened 2024-04-22 18:21 UTC by patricio0312rev

# [[transactions] handle multipayment transfer details](https://app.clickup.com/t/86dtb09k9)

## Summary

- Multipayment transactions are now supported on the details page.
- Multiple transaction-related components have been refactored.

<img width="355" alt="image" src="https://github.com/ArdentHQ/arkconnect-extension/assets/55117912/0b0dea37-3ca8-492d-bb37-f6ec605be8ce">

## Checklist

- [ ] I checked that both `pnpm dev` and `pnpm dev:bare` work as intended
- [ ] I checked the basic extension interactions and made sure wallet selection works
- [ ] I checked my UI changes against the design and there are no notable differences, including responsiveness
- [ ] I checked my (code) changes for obvious issues, debug statements and commented code
- [ ] I opened a corresponding card on Clickup for any remaining TODOs in my code
- [ ] I added a short description on how to test this PR _(if necessary)_
- [ ] Ready to be merged

2024-04-22 23:35 UTC, alfonsobries requested changes

2024-04-22 23:35 UTC, alfonsobries commented on src/components/transaction/details/AmountBadge.tsx
> +                    <div
Missing i18n

2024-04-23 08:36 UTC, samharperpittam approved these changes

2024-04-23 16:00 UTC, alfonsobries approved these changes

2024-04-23 16:05 UTC, merged