feat: add contact page
ArdentHQ/arkconnect-extension pull request #282
Opened 2024-05-07 15:55 UTC by patricio0312rev

# [[address book] new contact page](https://app.clickup.com/t/86dtbmv7f)

## Summary

- Language files have been updated.
- New `useAddressBook` custom hook.
- `Add new address` page has been added.

https://github.com/ArdentHQ/arkconnect-extension/assets/55117912/8dca7efe-3353-44c9-a0fa-35bb67e239f4

## Checklist

- [ ] I checked that both `pnpm dev` and `pnpm dev:bare` work as intended
- [ ] I checked the basic extension interactions and made sure wallet selection works
- [ ] I checked my UI changes against the design and there are no notable differences, including responsiveness
- [ ] I checked my (code) changes for obvious issues, debug statements and commented code
- [ ] I opened a corresponding card on Clickup for any remaining TODOs in my code
- [ ] I added a short description on how to test this PR _(if necessary)_
- [ ] Ready to be merged

2024-05-09 09:10 UTC, samharperpittam requested changes
Currently validation fails when attempting to add a devnet address. We should accept both mainnet and devnet addresses.

Spec:
```
Determine network based on the provided address and in the background store a network identifier for filtering later (mainnet/devnet).
```

2024-05-09 17:22 UTC, alfonsobries commented
1. You can add an addresss with spaces at the end
2. In some cases when I paste an address it shows a validation error for a second
3. Not sure if I missing one step but address doesn't seem to be stored, is that another task?


https://github.com/ArdentHQ/arkconnect-extension/assets/17262776/5c665b7e-6e53-4c0d-b590-4622ebcb65f2

2024-05-09 17:22 UTC, alfonsobries requested changes
See comments

2024-05-09 18:46 UTC, alfonsobries approved these changes

2024-05-10 10:12 UTC, samharperpittam approved these changes

2024-05-10 13:24 UTC, merged