feat: address book overview page
ArdentHQ/arkconnect-extension pull request #283
Opened 2024-05-07 19:54 UTC by patricio0312rev

# [[address book] addresses overview page](https://app.clickup.com/t/86dtbmvh9)

## Summary

- We now display the list of contacts if the address has any stored.

<img width="363" alt="image" src="https://github.com/ArdentHQ/arkconnect-extension/assets/55117912/c3775a40-5cf1-4f67-9610-cf01b81db4fe">

## Checklist

- [ ] I checked that both `pnpm dev` and `pnpm dev:bare` work as intended
- [ ] I checked the basic extension interactions and made sure wallet selection works
- [ ] I checked my UI changes against the design and there are no notable differences, including responsiveness
- [ ] I checked my (code) changes for obvious issues, debug statements and commented code
- [ ] I opened a corresponding card on Clickup for any remaining TODOs in my code
- [ ] I added a short description on how to test this PR _(if necessary)_
- [ ] Ready to be merged

2024-05-10 14:36 UTC, samharperpittam requested changes
The hover states for the edit buttons have been updated on figma as currently they blend in with the row hover state.

2024-05-10 14:41 UTC, samharperpittam requested changes
![image](https://github.com/ArdentHQ/arkconnect-extension/assets/44671015/ee938b7b-e7cb-46d6-beb4-24e39099b351)

may need a bit of truncation in the contact name to cover this scenario

2024-05-10 17:36 UTC, alfonsobries approved these changes
other than the hover style for edit button, rest looks ok

2024-05-13 08:42 UTC, samharperpittam approved these changes

2024-05-13 09:13 UTC, merged