feat: edit contact from address book
ArdentHQ/arkconnect-extension pull request #295
Opened 2024-05-13 13:34 UTC by patricio0312rev

# [[address book] handle edit](https://app.clickup.com/t/86dtbmvhc)

## Summary

- Depends on #294
- `Add Contact` page's components have been refactored.
- Types from the address book section have been moved to their own file.
- New `Edit Contact` page.

https://github.com/ArdentHQ/arkconnect-extension/assets/55117912/413fe45b-98ea-4c4d-9a35-a4a0e3ed49f8

## Checklist

- [ ] I checked that both `pnpm dev` and `pnpm dev:bare` work as intended
- [ ] I checked the basic extension interactions and made sure wallet selection works
- [ ] I checked my UI changes against the design and there are no notable differences, including responsiveness
- [ ] I checked my (code) changes for obvious issues, debug statements and commented code
- [ ] I opened a corresponding card on Clickup for any remaining TODOs in my code
- [ ] I added a short description on how to test this PR _(if necessary)_
- [ ] Ready to be merged

2024-05-14 07:30 UTC, ItsANameToo requested changes

2024-05-14 07:30 UTC, ItsANameToo commented on src/pages/EditContact.tsx
> +import { fetchValidateAddress } from './CreateContact';
added a card to refactor this: https://app.clickup.com/t/86dth2jgd

2024-05-14 07:30 UTC, ItsANameToo commented on src/pages/EditContact.tsx
> +            .min(34, t('ERROR.IS_INVALID', { name: 'Address' }))
34 min but also max

2024-05-14 12:20 UTC, ItsANameToo commented
conflict @patricio0312rev

2024-05-14 13:50 UTC, samharperpittam requested changes
When running `pnpm dev` and attempting to edit one of the seeded contacts, the edit functionality doesn't work (the form doesn't open). Is it possible to fix that?

However, editing a new contact that gets added works fine.

2024-05-14 13:54 UTC, samharperpittam requested changes
When editing a contact within the address book, if you modify the name of the contact, the edited name gets added as the address.

See video here: https://helloardent.slack.com/archives/C069X9DHWUR/p1715694763021289

2024-05-15 13:27 UTC, ItsANameToo commented
some conflicts @patricio0312rev

2024-05-15 17:27 UTC, merged