refactor: mimic Arkvault behaviour for address dropdown
ArdentHQ/arkconnect-extension pull request #307
Opened 2024-05-15 16:46 UTC by patricio0312rev

# [[send] mimic ARKVault behaviour for recipient field](https://app.clickup.com/t/86dth52r1)

## Summary

- We now display the dropdown list with suggestions when clicking on the display value to mimic ArkVault dropdown.

https://github.com/ArdentHQ/arkconnect-extension/assets/55117912/c0cedcd8-d1c4-4f11-ae14-eacd7451b688

## Checklist

- [ ] I checked that both `pnpm dev` and `pnpm dev:bare` work as intended
- [ ] I checked the basic extension interactions and made sure wallet selection works
- [ ] I checked my UI changes against the design and there are no notable differences, including responsiveness
- [ ] I checked my (code) changes for obvious issues, debug statements and commented code
- [ ] I opened a corresponding card on Clickup for any remaining TODOs in my code
- [ ] I added a short description on how to test this PR _(if necessary)_
- [ ] Ready to be merged

2024-05-15 21:36 UTC, alfonsobries approved these changes

2024-05-16 08:27 UTC, ItsANameToo requested changes

2024-05-16 08:27 UTC, ItsANameToo commented on src/components/send/AddressDropdown.tsx
> +        if (!inputValue || inputValue.length === 0 || inputValue.length === 34) {
better to use a constant instead of `34` so it's clear what the value indicates

2024-05-16 08:58 UTC, ItsANameToo approved these changes

2024-05-16 09:04 UTC, merged