refactor: display contacts per network
ArdentHQ/arkconnect-extension pull request #312
Opened 2024-05-19 18:10 UTC by patricio0312rev

# [[send] display contacts on the same network as sending address](https://app.clickup.com/t/86dtj2xre)

## Summary

- We now display the contacts filtered by the wallet's network on the address book dropdown.
- 
<img width="368" alt="image" src="https://github.com/ArdentHQ/arkconnect-extension/assets/55117912/fa590bb8-1cc1-4a8b-9850-295b3fdb3259">

## Checklist

- [ ] I checked that both `pnpm dev` and `pnpm dev:bare` work as intended
- [ ] I checked the basic extension interactions and made sure wallet selection works
- [ ] I checked my UI changes against the design and there are no notable differences, including responsiveness
- [ ] I checked my (code) changes for obvious issues, debug statements and commented code
- [ ] I opened a corresponding card on Clickup for any remaining TODOs in my code
- [ ] I added a short description on how to test this PR _(if necessary)_
- [ ] Ready to be merged

2024-05-20 10:25 UTC, samharperpittam approved these changes

2024-05-20 10:29 UTC, samharperpittam requested changes
It's possible for a devnet address to be displayed when only mainnet addresses should be. Do the following:

- `pnpm dev`
- Keep ARK 1 as primary wallet
- Add a devnet address to address book
- Go to Send form
- View dropdown
- See devnet address in list
- Change primary address to Testnet 1 
- Go to Send form
- View dropdown
- See no devnet address.

2024-05-21 08:29 UTC, ItsANameToo approved these changes

2024-05-21 08:30 UTC, ItsANameToo commented
lil conflict @patricio0312rev

2024-05-21 10:25 UTC, merged