feat: fee section for send page
ArdentHQ/arkconnect-extension pull request #314
Opened 2024-05-19 21:34 UTC by patricio0312rev

# [[send] add fee section](https://app.clickup.com/t/86dtbmv1q)

## Summary

- Fee section for `Send` page has been implemented.
- New `useNetworkFee` custom hook.

## Screenshots

- Simple fee options:
<img width="366" alt="image" src="https://github.com/ArdentHQ/arkconnect-extension/assets/55117912/528c0467-203e-45fc-a5cb-c127f39f9f7c">

- Advanced fee input:
<img width="366" alt="image" src="https://github.com/ArdentHQ/arkconnect-extension/assets/55117912/273ef503-b215-47f7-9769-c0a643ec94e6">

## Checklist

- [ ] I checked that both `pnpm dev` and `pnpm dev:bare` work as intended
- [ ] I checked the basic extension interactions and made sure wallet selection works
- [ ] I checked my UI changes against the design and there are no notable differences, including responsiveness
- [ ] I checked my (code) changes for obvious issues, debug statements and commented code
- [ ] I opened a corresponding card on Clickup for any remaining TODOs in my code
- [ ] I added a short description on how to test this PR _(if necessary)_
- [ ] Ready to be merged

2024-05-20 13:42 UTC, shahin-hq commented
In PSDK we have exposed methods to get the fee, please use them to get the fee https://github.com/ArdentHQ/arkvault/blob/693ed0a505b69069525a3011bf1270b77aedc790/src/app/hooks/use-fees.ts#L98

2024-05-20 13:53 UTC, alfonsobries commented on package.json
> +        "bignumber.js": "^9.1.2",
@patricio0312rev I think the sdk already has a instance of big number, at lest some equivalente implementation

`import { BigNumber } from "@ardenthq/sdk-helpers";`

See arkvault for reference https://github.com/search?q=repo%3AArdentHQ%2Farkvault%20BigNumber&type=code

2024-05-20 13:55 UTC, alfonsobries requested changes

2024-05-20 13:55 UTC, alfonsobries commented on src/components/send/SendForm.tsx
> +                helperText={formik.errors.amount && formik.values.amount && formik.errors.amount}
you probably meant 

```suggestion
                helperText={formik.errors.amount && formik.values.amount}
```

2024-05-20 14:13 UTC, alfonsobries requested changes
The "Max" button is not considering the selected fee causing an error, also depending on the scope of this task we need to adjust the max value if the fee changes, so for example if I press max and the I change the fee the max value should change 

<img width="426" alt="image" src="https://github.com/ArdentHQ/arkconnect-extension/assets/17262776/a5423630-98b5-46e8-8a4e-9329b0dadcdc">

2024-05-21 12:11 UTC, ItsANameToo requested changes

2024-05-21 12:11 UTC, ItsANameToo commented on src/lib/hooks/useNetworkFees.ts
> +    const getMuSigData = (senderWallet: Contracts.IReadWriteWallet, data: Record<string, any>) => {
we don't need musig related stuff at this time, it's not supported in arkconnect

2024-05-21 12:11 UTC, ItsANameToo commented on src/lib/hooks/useNetworkFees.ts
> +                (coinInstance.network().feeType() === 'size' || type === 'multiSignature')
pretty much everything related to musig can go, likewise for the `size` feetype as that's not used on ark at this time either

2024-05-21 12:11 UTC, ItsANameToo commented on src/pages/Send.tsx
> +            .matches(/^[0-9]+(\.[0-9]{1,8})?$/, {
maybe move the regex out to a constant with a descriptive name, as it's used twice

2024-05-21 12:11 UTC, ItsANameToo commented on src/lib/hooks/useNetworkFees.ts
> +import { Coins, Services } from '@ardenthq/sdk';
general remark for this file, have a look at what's really necessary from here for arkconnect and strip out the rest to avoid obsolete code

2024-05-21 14:22 UTC, ItsANameToo approved these changes

2024-05-21 15:03 UTC, samharperpittam approved these changes

2024-05-21 15:14 UTC, merged