fix: remove double outline in dark mode
ArdentHQ/arkconnect-extension pull request #34
Opened 2024-02-27 22:14 UTC by patricio0312rev

[[extension] sanity check accessibility](https://app.clickup.com/t/86drk4r60)

## Summary

- Double outline in dark mode has been fixed.

## Screenshots

- Before:
<img width="363" alt="image" src="https://github.com/ArdentHQ/arkconnect-extension/assets/55117912/c11a162c-e2dc-4259-8668-967617bae4da">

- After:
<img width="360" alt="image" src="https://github.com/ArdentHQ/arkconnect-extension/assets/55117912/b9457de6-b94e-4559-a22c-ac05deed1504">

## Checklist

- [ ] I checked that both `pnpm dev` and `pnpm dev:bare` work as intended
- [ ] I checked the basic extension interactions and made sure wallet selection works
- [ ] I checked my UI changes against the design and there are no notable differences, including responsiveness
- [ ] I checked my (code) changes for obvious issues, debug statements and commented code
- [ ] I opened a corresponding card on Clickup for any remaining TODOs in my code
- [ ] I added a short description on how to test this PR _(if necessary)_
- [ ] Ready to be merged

2024-02-28 00:16 UTC, alexbarnsley requested changes
![image](https://github.com/ArdentHQ/arkconnect-extension/assets/8069294/f765c219-8b7f-488b-9f02-e9e290166b98)

There's a white outline on the network selection modal

-----------

I'm not sure if it's related to this but there could do with a transition on this too. When tabbing, there is a green outline and then it looks like a second green outline appears.

2024-02-28 15:33 UTC, alexbarnsley requested changes
Just one issue that I've noticed - the outline isn't complete for setting list entries :thinking: 

![image](https://github.com/ArdentHQ/arkconnect-extension/assets/8069294/2f8f3b27-418a-4e9b-a433-10dc7c6d73b4)

2024-02-29 10:50 UTC, ItsANameToo commented
the row hover state can also end up above the border, which looks weird 
<img width="356" alt="image" src="https://github.com/ArdentHQ/arkconnect-extension/assets/35610748/a25f77fc-5193-4a9b-b1d7-d10f1eaeca34">

2024-02-29 12:23 UTC, ItsANameToo approved these changes

2024-02-29 13:33 UTC, alexbarnsley approved these changes

2024-02-29 13:34 UTC, merged