fix: adjust scrollbar color in firefox
ArdentHQ/arkconnect-extension pull request #380
Opened 2024-06-06 09:52 UTC by patricio0312rev

# [[general] green scrollbars with blue theme on firefox](https://app.clickup.com/t/86dtr0k09)

## Summary

- CSS styles for custom scroll bar have been updated for the following themes: light w/ blue & dark w/blue.

![image](https://github.com/ArdentHQ/arkconnect-extension/assets/55117912/959acae5-ba98-4a53-b6c6-909868940ed3)
![image](https://github.com/ArdentHQ/arkconnect-extension/assets/55117912/37266e71-9bea-4cc4-9075-89b940b4ac8c)

## Checklist

- [ ] I checked that both `pnpm dev` and `pnpm dev:bare` work as intended
- [ ] I checked the basic extension interactions and made sure wallet selection works
- [ ] I checked my UI changes against the design and there are no notable differences, including responsiveness
- [ ] I checked my (code) changes for obvious issues, debug statements and commented code
- [ ] I opened a corresponding card on Clickup for any remaining TODOs in my code
- [ ] I added a short description on how to test this PR _(if necessary)_
- [ ] Ready to be merged

2024-06-06 10:36 UTC, ItsANameToo requested changes

2024-06-06 10:36 UTC, ItsANameToo commented on src/main.css
>          scrollbar-color: #058751 transparent;
could we rely on the `var(..)` method here to refer to the colors defined in the themes? might simplify it

2024-06-06 17:37 UTC, alfonsobries approved these changes

2024-06-07 09:37 UTC, ItsANameToo commented on src/main.css
>          scrollbar-color: #058751 transparent;
fixed it by adding `rgb()` around it, seems it didn't like the hex one for some reason in firefox

2024-06-07 09:38 UTC, ItsANameToo approved these changes

2024-06-07 09:40 UTC, merged