refactor: low fee warning
ArdentHQ/arkconnect-extension pull request #402
Opened 2024-06-13 18:45 UTC by patricio0312rev

# [[general] implement warnings when fee is too low](https://app.clickup.com/t/86dttwe1j)

## Summary

- An alert and a warning banner will display when the fee is lower than the `Slow` preset.

<img width="367" alt="image" src="https://github.com/ArdentHQ/arkconnect-extension/assets/55117912/6cc3e5b4-9cbb-44a5-b10e-8bc093b37ffb">

## Checklist

- [ ] I checked that both `pnpm dev` and `pnpm dev:bare` work as intended
- [ ] I checked the basic extension interactions and made sure wallet selection works
- [ ] I checked my UI changes against the design and there are no notable differences, including responsiveness
- [ ] I checked my (code) changes for obvious issues, debug statements and commented code
- [ ] I opened a corresponding card on Clickup for any remaining TODOs in my code
- [ ] I added a short description on how to test this PR _(if necessary)_
- [ ] Ready to be merged

2024-06-14 09:43 UTC, samharperpittam reviewed
@patricio0312rev 

I get a fee warning when using the "Slow" preset when sending a tx on devnet. 

![image](https://github.com/ArdentHQ/arkconnect-extension/assets/44671015/a3c55a67-d509-4a0d-b0fd-e39158791bc4)

Unless i'm misunderstanding the implementation, shouldn't the warning only be displayed if the user enters a manual fee under the "Slow" preset?

2024-06-14 11:42 UTC, ItsANameToo requested changes

2024-06-14 11:42 UTC, ItsANameToo commented on src/components/approve/CustomFeeAlerts.blocks.tsx
> +                    })}
did this not work on a single line without splitting it up in translation files? 🤔

2024-06-14 11:42 UTC, ItsANameToo commented on src/components/approve/ApproveLayout.tsx
> +        : null;
this should be a translation, not a constant. Otherwise it will output `higher` and `lower` in english at all times

2024-06-17 10:22 UTC, ItsANameToo approved these changes

2024-06-17 10:22 UTC, merged