fix: prevent theme from changing when addresses are removed
ArdentHQ/arkconnect-extension pull request #426
Opened 2024-07-04 13:09 UTC by patricio0312rev

# [[general] prevent theme from changing to blue when wallets are deleted](https://app.clickup.com/t/86du1qy9a)

## Summary

- The theme color won't change when all the addresses are removed from the wallet.

https://github.com/ArdentHQ/arkconnect-extension/assets/55117912/fdf7c7a1-7a15-4590-9783-af4ece3adb43

## Checklist

- [ ] I checked that both `pnpm dev` and `pnpm dev:bare` work as intended
- [ ] I checked the basic extension interactions and made sure wallet selection works
- [ ] I checked my UI changes against the design and there are no notable differences, including responsiveness
- [ ] I checked my (code) changes for obvious issues, debug statements and commented code
- [ ] I opened a corresponding card on Clickup for any remaining TODOs in my code
- [ ] I added a short description on how to test this PR _(if necessary)_
- [ ] Ready to be merged

2024-07-04 13:30 UTC, samharperpittam approved these changes

2024-07-04 13:38 UTC, samharperpittam requested changes
@patricio0312rev  - whilst this change resolves the issue that the theme no longer changes when all addresses are removed. It also prevents the theme from resetting when the user performs a Reset (via Forgot Password).

Is it possible to have two different scenarios handled in different ways for this?

**Scenario 1 - Wallet Removal**
In a scenario where the user removes all wallets from their profile, all previous profile settings remain the same (Currency, Sleep Timer, Theme etc) but the user is navigated to the onboarding page again as they have 0 wallets added to their profile. 

**Scenario 2 - Profile Reset**
In a scenario where the user forgets their password and uses the "Reset" function, all profile setting should be reset at this point (Theme, Currency, etc etc) and the extension should behave as if it's the first time it's been launched. 

Thoughts?

2024-07-05 09:15 UTC, samharperpittam approved these changes
Nice work @patricio0312rev !

2024-07-05 12:59 UTC, ItsANameToo approved these changes

2024-07-05 12:59 UTC, merged