refactor: tailwind for icon component
ArdentHQ/arkconnect-extension pull request #43
Opened 2024-02-28 23:46 UTC by patricio0312rev

# [[extension] icon component tailwind refactor](https://app.clickup.com/t/86drqmg9n)

## Summary

- Depends on #44  and #38 
- Icon component has been refactored and now works with tailwind classes.
- All the implementations of this component have been refactored.

## Checklist

- [ ] I checked that both `pnpm dev` and `pnpm dev:bare` work as intended
- [ ] I checked the basic extension interactions and made sure wallet selection works
- [ ] I checked my UI changes against the design and there are no notable differences, including responsiveness
- [ ] I checked my (code) changes for obvious issues, debug statements and commented code
- [ ] I opened a corresponding card on Clickup for any remaining TODOs in my code
- [ ] I added a short description on how to test this PR _(if necessary)_
- [ ] Ready to be merged

2024-02-29 08:21 UTC, ItsANameToo commented
Draft until #44 is merged

2024-02-29 10:15 UTC, shahin-hq commented on src/shared/components/icon/index.tsx
>      style?: React.CSSProperties;
I think we can remove `style` as well since we are using classes to style things

2024-02-29 15:28 UTC, alfonsobries requested changes
Not sure if introduced on this pr but the back button is invisible apparently everywhere, on the screenshot you can see the "hover" style, if I dont hover it is invisible

![image](https://github.com/ArdentHQ/arkconnect-extension/assets/17262776/eacf6371-a6ee-4fe1-bcfa-989c507bd426)

2024-02-29 15:32 UTC, alfonsobries commented
connect to app icon is now lighter

Before

![image](https://github.com/ArdentHQ/arkconnect-extension/assets/17262776/57333070-a56b-4fa5-a563-56a8c87b4e83)

After
![image](https://github.com/ArdentHQ/arkconnect-extension/assets/17262776/ce4c54da-b6d6-443e-babc-16dbf61fca47)

2024-02-29 15:34 UTC, alfonsobries commented
rest of actions icons are lighter as well
![image](https://github.com/ArdentHQ/arkconnect-extension/assets/17262776/33b4c7bb-b5a2-4b41-84c1-ff020955776f)

2024-02-29 15:36 UTC, alfonsobries commented
main logo is lighter 
![image](https://github.com/ArdentHQ/arkconnect-extension/assets/17262776/ce0eaf32-3c1b-49c3-9f50-643a83d3593c)

2024-02-29 15:37 UTC, alfonsobries commented
another that is lighter
![image](https://github.com/ArdentHQ/arkconnect-extension/assets/17262776/b88c89b4-fd30-4fd5-b042-950ab70eb620)

2024-03-04 10:26 UTC, ItsANameToo commented on src/shared/components/icon/index.tsx
> +        <span {...rest} className={cn('block', 'Icon ' + (className ? className : ''))} role='img'>
removed it

2024-03-04 10:31 UTC, merged