refactor: add outline to primary and destructive buttons
ArdentHQ/arkconnect-extension pull request #56
Opened 2024-02-29 21:08 UTC by alfonsobries

## Summary

Closes https://app.clickup.com/t/86drqvknr https://app.clickup.com/t/86drqvkh0

Currently keeping the shadow but think look odd so design may be adjusted, making a pr so can be seen

![image](https://github.com/ArdentHQ/arkconnect-extension/assets/17262776/8f9dbedc-0bfb-43ff-b51e-ca37620ccf24)

![image](https://github.com/ArdentHQ/arkconnect-extension/assets/17262776/214b13a0-7091-42b4-b53b-20efcca5275f)
![image](https://github.com/ArdentHQ/arkconnect-extension/assets/17262776/70c74627-cb59-433c-8c09-1763a41d1734)
![image](https://github.com/ArdentHQ/arkconnect-extension/assets/17262776/143cff6f-9c25-4dc2-bad3-3140fdf26faa)

## Checklist

- [ ] I checked that both `pnpm dev` and `pnpm dev:bare` work as intended
- [ ] I checked the basic extension interactions and made sure wallet selection works
- [ ] I checked my UI changes against the design and there are no notable differences, including responsiveness
- [ ] I checked my (code) changes for obvious issues, debug statements and commented code
- [ ] I opened a corresponding card on Clickup for any remaining TODOs in my code
- [ ] I added a short description on how to test this PR _(if necessary)_
- [ ] Ready to be merged

2024-02-29 21:32 UTC, ItsANameToo requested changes
for button highlight I'd try:
- to make the "destructive" outline red
- have a 1px gap between the button element and the outline so it's doesn't become part of the button

2024-03-04 17:21 UTC, alfonsobries commented
@ItsANameToo 

updated to this

![image](https://github.com/ArdentHQ/arkconnect-extension/assets/17262776/9444d2ac-d170-4986-8746-2fbd9c33aad8)

![image](https://github.com/ArdentHQ/arkconnect-extension/assets/17262776/45804a20-9a41-4997-bbb4-803455ae48b7)

![image](https://github.com/ArdentHQ/arkconnect-extension/assets/17262776/e388adf1-4201-4fdf-8e88-c737ba662182)



thinks also looks weird but at least the last one, but not sure maybe I just get to use to 🤔

2024-03-05 09:37 UTC, ItsANameToo approved these changes

2024-03-05 09:37 UTC, ItsANameToo commented
improvement to what it was before, we'll further finetune later

2024-03-05 09:37 UTC, merged