refactor: cache coingecko response
ArdentHQ/arkconnect-extension pull request #8
Opened 2024-02-26 13:31 UTC by alfonsobries

## Summary

Closes https://app.clickup.com/t/86drmrzxh

## Checklist

- [ ] I checked that both `pnpm dev` and `pnpm dev:bare` work as intended
- [ ] I checked the basic extension interactions and made sure wallet selection works
- [ ] I checked my UI changes against the design and there are no notable differences, including responsiveness
- [ ] I checked my (code) changes for obvious issues, debug statements and commented code
- [ ] I opened a corresponding card on Clickup for any remaining TODOs in my code
- [ ] I added a short description on how to test this PR _(if necessary)_
- [ ] Ready to be merged

2024-02-27 17:31 UTC, alfonsobries commented
@shahin-hq I completely refactored the hook, I also wasn't considering the maximum number of requests per minute, meaning I was making 1 request per minute instead of N. Could you check again please?

2024-02-27 23:30 UTC, alexbarnsley requested changes
I refreshed the extension a few times and eventually got throttled :thinking: if it matters, I'm running 3 mainnet wallets

![image](https://github.com/ArdentHQ/arkconnect-extension/assets/8069294/0e6e648a-be8b-4e00-a41f-a12e567ca97c)

I seem to get the coingecko request on every refresh. It appears that the cache isn't being used after ~1 minute. I've requested changes but if it's user error feel free to dismiss it

2024-02-28 14:00 UTC, shahin-hq commented on src/lib/hooks/useExchangeRates.ts
> +                }
```javascript
                if (ratesCache.requestCount < MAX_COINGECKO_REQUESTS_PER_MINUTE) {
                    ratesCache.rates = await fetchRates();
                    ratesCache.requestCount += 1;
                } else {
                    // If MAX_COINGECKO_REQUESTS_PER_MINUTE is reached, use cached rates
                    setRates(ratesCache.rates);
                    setLoading(false);
                    return;
                }
```

What do you think about removing this part?  1 min data is fresh enough I think, I wouldn't keep sending 10 requests in a minute - even it is allowed.

2024-02-28 14:17 UTC, alfonsobries commented
@goga-m by using 1 req per minute the logic is going to be simpler so think is not going to be necessary

2024-02-28 14:34 UTC, alfonsobries commented
@alexbarnsley the error you had was because a bad merge fixed that and changed the logic to only make one req per minute, should be fine now 

cc @shahin-hq

2024-02-28 14:50 UTC, shahin-hq approved these changes

2024-02-28 15:38 UTC, alexbarnsley approved these changes

2024-02-29 09:27 UTC, ItsANameToo approved these changes

2024-02-29 09:27 UTC, merged